const Products = [
  {
    id: 1,
    name: "Men's T-Shirt",
    brand: "Nike",
    Price: 999,
    category: "Clothing",
    genre: "Men",
  },
  {
    id: 2,
    name: "Women's T-Shirt",
    brand: "Nike",
    Price: 999,
    category: "Clothing",
    genre: "Women",
  },
  {
    id: 3,
    name: "T-Shirt",
    brand: "Nike",
    Price: 999,
    category: "Clothing",
    genre: "Both",
  },
  {
    id: 4,
    name: "Stuts",
    brand: "Adidas",
    Price: 9999,
    category: "Footwear",
    genre: "Both",
  },
  {
    id: 5,
    name: "Top",
    brand: "Addidas",
    Price: 2124,
    category: "Clothing",
    genre: "Women",
  },
  {
    id: 6,
    name: "Trousers",
    brand: "Budda Jeans",
    Price: 6452,
    category: "Clothing",
    genre: "Both",
  },
  {
    id: 7,
    name: "Leggies",
    brand: "Mike",
    Price: 999,
    category: "Clothing",
    genre: "Wowen",
  },
  {
    id: 8,
    name: "Watch",
    brand: "Hertz",
    Price: 8888,
    category: "Watch",
    genre: "Men",
  },
  {
    id: 9,
    name: "Watch",
    brand: "Spark",
    Price: 7776,
    category: "Watch",
    genre: "Women",
  },
  {
    id: 10,
    name: "InnerWear",
    brand: "Amul Macho",
    Price: 999,
    category: "Clothing",
    genre: "Men",
  },
  {
    id: 11,
    name: "InnerWear",
    brand: "leggy",
    Price: 999,
    category: "Clothing",
    genre: "Women",
  },
  {
    id: 12,
    name: "Globes",
    brand: "SG",
    Price: 999,
    category: "Clothing",
    genre: "Both",
  },
  {
    id: 13,
    name: "Air Jordan",
    brand: "Nike",
    Price: 9990,
    category: "Footwear",
    genre: "Men",
  },
  {
    id: 14,
    name: "Shirt",
    brand: "Reybonds",
    Price: 9849,
    category: "Clothing",
    genre: "Men",
  },
  {
    id: 15,
    name: "Suits",
    brand: "Random",
    Price: 999,
    category: "Clothing",
    genre: "Women",
  },
  {
    id: 16,
    name: "Tie",
    brand: "Some",
    Price: 999,
    category: "Clothing",
    genre: "Both",
  },
  {
    id: 17,
    name: "Lungi",
    brand: "Indian",
    Price: 999,
    category: "Clothing",
    genre: "Men",
  },
  {
    id: 18,
    name: "Saare",
    brand: "Indian",
    Price: 999,
    category: "Clothing",
    genre: "Women",
  },
];

module.exports = Products;
